name: Day 2 - Workflow Anatomy

on:
  push:
    branches:
      - main

jobs:
  anatomy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Print date
        run: date

      - name: Step 2 - Print working directory
        run: pwd

      - name: Step 3 - List files
        run: ls -la
